version: "3.9"

services:
  migrations-complex:
    image: reportportal/migrations-complex:latest
    environment:
      RP_STORAGE_MIGRATION: "true"

      RP_DB_HOST: ${RP_DB_HOST}
      RP_DB_USER: ${RP_DB_USER}
      RP_DB_PASS: ${RP_DB_PASS}
      RP_DB_NAME: ${RP_DB_NAME}

      DATASTORE_BUCKETPREFIX: ${DATASTORE_BUCKETPREFIX:-prj-}
      DATASTORE_DEFAULTBUCKETNAME: ${DATASTORE_DEFAULTBUCKETNAME:-rp-bucket}
      DATASTORE_SINGLEBUCKETNAME: ${DATASTORE_SINGLEBUCKETNAME}
      DATASTORE_REGION: ${DATASTORE_REGION}
      DATASTORE_REMOVE_AFTER_MIGRATION: ${DATASTORE_REMOVE_AFTER_MIGRATION:-false}

      MIGRATION_STORAGE_SOURCE_ACCESSKEY: ${MIGRATION_STORAGE_SOURCE_ACCESSKEY}
      MIGRATION_STORAGE_SOURCE_SECRETKEY: ${MIGRATION_STORAGE_SOURCE_SECRETKEY}
      MIGRATION_STORAGE_SOURCE_ENDPOINT: ${MIGRATION_STORAGE_SOURCE_ENDPOINT}
      MIGRATION_STORAGE_SOURCE_REGION: ${MIGRATION_STORAGE_SOURCE_REGION:-us-east-1}

      MIGRATION_STORAGE_DESTINATION_ACCESSKEY: ${MIGRATION_STORAGE_DESTINATION_ACCESSKEY}
      MIGRATION_STORAGE_DESTINATION_SECRETKEY: ${MIGRATION_STORAGE_DESTINATION_SECRETKEY}
      MIGRATION_STORAGE_DESTINATION_REGION: ${MIGRATION_STORAGE_DESTINATION_REGION}
      MIGRATION_STORAGE_DESTINATION_ENDPOINT: ${MIGRATION_STORAGE_DESTINATION_ENDPOINT:-}

    restart: "no"
