apiVersion: v2
name: migrations-complex
description: Report Portral Migrations Complex Service
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://github.com/reportportal/migrations-complex
keywords:
  - reportportal
  - migrations-complex
maintainers:
  - name: reportportal
    email: support@reportportal.io
