name: Release Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/workflows/chart-release.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'reportportal.io'
          email: 'support@reportportal.io'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
