name: Retag RC Docker image

on:
  pull_request_review:
    types: [submitted]

jobs:
  release:
    if: >
      github.event.review.state == 'approved'
    uses: reportportal/.github/.github/workflows/dockerhub-release.yaml@feature/EPMRPP-110955
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      REGESTRY_USERNAME: ${{ secrets.DOCKERHUB_PASSWORD }}
      REGESTRY_PASSWORD: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      aws-region: ${{ vars.AWS_REGION }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      target-registry: ${{ vars.TARGET_REGISTRY || 'docker.io' }}
      target-repository: ${{ vars.TARGET_REPOSITORY || 'reportportal/migrations-complex' }}
      platforms: ${{ vars.BUILD_PLATFORMS }}
      release-mode: rc