name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      scripts_version:
        description: 'Gradle scripts version'
        required: true

env:
  GH_USER_NAME: github.actor
  SCRIPTS_VERSION: ${{ github.event.inputs.scripts_version }}
  RELEASE_VERSION: ${{ github.event.inputs.version }}
  REPOSITORY_URL: 'https://maven.pkg.github.com/'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          name: 'reportportal.io'
          email: 'support@reportportal.io'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: .
